/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import archivo.Escritor;
import archivo.Lector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import logica.Alcancia;

/**
 *
 * @author Nicolas
 */
public class Main extends javax.swing.JFrame {
    
    private Alcancia alcancia;
    private Lector lector = new Lector();
    private Escritor escritor = new Escritor();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        this.alcancia = lector.leer();
        if(alcancia == null) {
            this.btnAgregar.setEnabled(false);
            this.btnInfo.setEnabled(false);
            this.btnRomper.setEnabled(false);
            lblCantidad.setText("");
        } else {
            this.btnNueva.setEnabled(false);
            lblCantidad.setText("Cantidad total de monedas dentro: " + alcancia.contarMonedas());
        }
        
        setTitle("MiAlcancia - Nicolas Olarte");
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/img/agregar.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblCantidad = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        rbtn50 = new javax.swing.JRadioButton();
        rbtn100 = new javax.swing.JRadioButton();
        rbtn200 = new javax.swing.JRadioButton();
        rbtn500 = new javax.swing.JRadioButton();
        rbtn1000 = new javax.swing.JRadioButton();
        lblMoneda = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnRomper = new javax.swing.JButton();
        btnNueva = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        lblContador = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCantidad.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("Cantidad total de monedas dentro: ");

        lblValor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblValor.setText("Selecciona el valor de la moneda:");

        btnGroup.add(rbtn50);
        rbtn50.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbtn50.setSelected(true);
        rbtn50.setText("$50");
        rbtn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn50ActionPerformed(evt);
            }
        });

        btnGroup.add(rbtn100);
        rbtn100.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbtn100.setText("$100");
        rbtn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn100ActionPerformed(evt);
            }
        });

        btnGroup.add(rbtn200);
        rbtn200.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbtn200.setText("$200");
        rbtn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn200ActionPerformed(evt);
            }
        });

        btnGroup.add(rbtn500);
        rbtn500.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbtn500.setText("$500");
        rbtn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn500ActionPerformed(evt);
            }
        });

        btnGroup.add(rbtn1000);
        rbtn1000.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbtn1000.setText("$1000");
        rbtn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn1000ActionPerformed(evt);
            }
        });

        lblMoneda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/50.png"))); // NOI18N

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btnAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar moneda seleccionada", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Roboto", 1, 10))); // NOI18N
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRomper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/romper.png"))); // NOI18N
        btnRomper.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Romper alcancía", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Roboto", 1, 10))); // NOI18N
        btnRomper.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnRomper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRomperActionPerformed(evt);
            }
        });

        btnNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nueva.png"))); // NOI18N
        btnNueva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva alcancía", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Roboto", 1, 10))); // NOI18N
        btnNueva.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/izquierda.png"))); // NOI18N
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/derecha.png"))); // NOI18N
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });

        lblContador.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContador.setText("0");

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion.png"))); // NOI18N
        btnInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ver información de la moneda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Roboto", 1, 10))); // NOI18N
        btnInfo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Cantidad: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRomper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbtn50, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn100, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn200, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn500, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn1000, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMoneda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(btnNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtn50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn200)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn500)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtn1000)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDerecha)
                            .addComponent(lblContador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIzquierda)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInfo)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNueva)
                    .addComponent(btnRomper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn50ActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/50.png"));
        this.lblMoneda.setIcon(icon);
    }//GEN-LAST:event_rbtn50ActionPerformed

    private void rbtn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn100ActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/100.png"));
        this.lblMoneda.setIcon(icon);
    }//GEN-LAST:event_rbtn100ActionPerformed

    private void rbtn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn200ActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/200.png"));
        this.lblMoneda.setIcon(icon);
    }//GEN-LAST:event_rbtn200ActionPerformed

    private void rbtn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn500ActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/500.png"));
        this.lblMoneda.setIcon(icon);
    }//GEN-LAST:event_rbtn500ActionPerformed

    private void rbtn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn1000ActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/1000.png"));
        this.lblMoneda.setIcon(icon);
    }//GEN-LAST:event_rbtn1000ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(!rbtn50.isSelected() && !rbtn100.isSelected() && !rbtn200.isSelected() && !rbtn500.isSelected() && !rbtn1000.isSelected()) {
            JOptionPane.showMessageDialog(null, "Por favor selecciona una moneda...", "Agregar Moneda", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int cantidad = Integer.parseInt(lblContador.getText());
        
        if(cantidad == 0) {
            JOptionPane.showMessageDialog(null, "La cantidad no debe ser cero ;)", "Agregar Moneda", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int valor = 0;
        
        if(rbtn50.isSelected()){
            valor = 50;
            alcancia.agregarMoneda(valor,cantidad);
        }
        if(rbtn100.isSelected()){
            valor = 100;
            alcancia.agregarMoneda(valor,cantidad);
        }
        if(rbtn200.isSelected()){
            valor = 200;
            alcancia.agregarMoneda(valor,cantidad);
        }
        if(rbtn500.isSelected()){
            valor = 500;
            alcancia.agregarMoneda(valor,cantidad);
        }
        if(rbtn1000.isSelected()){
            valor = 1000;
            alcancia.agregarMoneda(valor,cantidad);
        }
        
        JOptionPane.showMessageDialog(null, "Has agregado "+cantidad+" moneda(s) de $"+valor+".", "Agregar Moneda", JOptionPane.INFORMATION_MESSAGE);
        this.escritor.guardar(this.alcancia);
        
        lblContador.setText("0");
        lblCantidad.setText("Cantidad total de monedas dentro: " + alcancia.contarMonedas());
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRomperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRomperActionPerformed
        int aux = JOptionPane.showConfirmDialog(null, "¿Realmente deseas romper tu alcacía?", "Romper Alcancía", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(aux != 0) return;
        
        lblCantidad.setText("Tenías un total de: $"+this.alcancia.calcularTotal());
        this.alcancia = null;
        this.escritor.guardar(this.alcancia);
        this.btnAgregar.setEnabled(false);
        this.btnInfo.setEnabled(false);
        this.btnRomper.setEnabled(false);
        this.btnNueva.setEnabled(true);
    }//GEN-LAST:event_btnRomperActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        if(!rbtn50.isSelected() && !rbtn100.isSelected() && !rbtn200.isSelected() && !rbtn500.isSelected() && !rbtn1000.isSelected()) {
            JOptionPane.showMessageDialog(null, "Por favor selecciona una moneda...", "Agregar Moneda", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int valor = 0;
        
        if(rbtn50.isSelected()) valor = 50;
        if(rbtn100.isSelected()) valor = 100;
        if(rbtn200.isSelected()) valor = 200;
        if(rbtn500.isSelected()) valor = 500;
        if(rbtn1000.isSelected()) valor = 1000;
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/"+valor+"rev.png"));
        int cantidad = alcancia.getMonedas(valor);
        String aux = "Tienes "+cantidad+" monedas de esta denominación.\nTotal de dinero en estas: $"+valor*cantidad+".";
        JOptionPane.showMessageDialog(rootPane, aux, "Información de la Moneda", JOptionPane.PLAIN_MESSAGE, icon);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        if(lblContador.getText().equals("0"))
            return;
        
        int cantidad = Integer.parseInt(lblContador.getText()) - 1;
        lblContador.setText(""+cantidad);
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        int cantidad = Integer.parseInt(lblContador.getText()) + 1;
        lblContador.setText(""+cantidad);
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
        this.alcancia = new Alcancia();
        this.escritor.guardar(this.alcancia);
        this.btnAgregar.setEnabled(true);
        this.btnInfo.setEnabled(true);
        this.btnRomper.setEnabled(true);
        this.btnNueva.setEnabled(false);
        lblCantidad.setText("Cantidad total de monedas dentro: 0");
    }//GEN-LAST:event_btnNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDerecha;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JButton btnNueva;
    private javax.swing.JButton btnRomper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton rbtn100;
    private javax.swing.JRadioButton rbtn1000;
    private javax.swing.JRadioButton rbtn200;
    private javax.swing.JRadioButton rbtn50;
    private javax.swing.JRadioButton rbtn500;
    // End of variables declaration//GEN-END:variables
}
